GET http://localhost:6869/index


### login user
POST http://localhost:6869/api/v1/users/login
Content-Type: application/json

{"username": "alex", "password": "test-pwd123@#"}


### regiser user
POST http://localhost:6869/api/v1/users/register
Content-Type: application/json

{"username": "xiaoming_123", "password": "test-Pwd123@#", "avatar": "http://localhost:6869/imgs/alex_avatar.png", "display_name": "Xiao Ming"}


### create channel
POST http://localhost:6869/api/v1/channels
Content-Type: application/json

{"ch_name": "learn-rust-chan2", "ch_desc": "Let's learn rust", "is_private": false, "creator_id": 2}

### list channels
GET http://localhost:6869/api/v1/channels
Content-Type: application/json

{"creator_id": 3}


### get channels
GET http://localhost:6869/api/v1/channels/1
Content-Type: application/json

### join channel
POST http://localhost:6869/api/v1/channels/join
Content-Type: application/json

{"user_id": 3, "chan_id": 1}

### list message
GET http://localhost:6869/api/v1/channels/2/messages
Content-Type: application/json

{"offset": 0, "limit": 100}


### send message
POST http://localhost:6869/api/v1/channels/1/messages
Content-Type: application/json

{"sender_id": 1, "parent_msg_id": null, "content_type": "text", "text_content": "Hello Hello", "media_url": "https://slac.com/videos/video1.mp4", "media_metadata": {"width": 500, "height": 600, "format": "mp4"}}