GET http://localhost:6869/index


### login user
POST http://localhost:6869/api/v1/users/login
Content-Type: application/json

{"username": "Smith_123", "password": "test-Pwd123@#"}


### regiser user
POST http://localhost:6869/api/v1/users/register
Content-Type: application/json

{"username": "Smith_123", "password": "test", "avatar": "http://localhost:6869/imgs/alice_avatar.png", "display_name": "SMS"}


### get user
GET http://localhost:6869/api/v1/users/6
Content-Type: application/json


### create channel
POST http://localhost:6869/api/v1/channels
Content-Type: application/json

{"ch_name": "learn-rust-chan2", "ch_desc": "Let's learn rust", "is_private": false, "creator_id": 2}

### list channels
GET http://localhost:6869/api/v1/channels
Content-Type: application/json

{"creator_id": 3}


### get channels
GET http://localhost:6869/api/v1/channels/1
Content-Type: application/json

### list channel members
GET http://localhost:6869/api/v1/channels/1/members
Content-Type: application/json

### join channel
POST http://localhost:6869/api/v1/channels/1/join
Content-Type: application/json

{"user_id": 5}

### leave channel
DELETE http://localhost:6869/api/v1/channels/1/leave
Content-Type: application/json

{"user_id": 5}

### list message
GET http://localhost:6869/api/v1/channels/1/messages
Content-Type: application/json

{"offset": 0, "limit": 10}


### get message
GET http://localhost:6869/api/v1/messages/10
Content-Type: application/json


### send message
POST http://localhost:6869/api/v1/channels/1/messages
Content-Type: application/json

{"sender_id": 1, "parent_msg_id": null, "content_type": "text", "text_content": "Hello Hello", "media_url": "https://slac.com/videos/video1.mp4", "media_metadata": {"width": 500, "height": 600, "format": "mp4"}}